[package]
build = './common/build/build.rs'
description = 'RLDP library'
edition = '2021'
name = 'rldp'
version = '0.7.128'

[workspace]


[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
log = '0.4'
rand = '0.7'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ever-adnl.git', tag = '0.7.133' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-crypto.git', tag = '0.1.92' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
raptorq = { path = 'raptorq', version = '1.2.1' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ever-tl.git', package = 'ton_api', tag = '0.2.179' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '1.12.7' }

[features]
telemetry = [ 'adnl/telemetry' ]

