[package]
build = './common/build/build.rs'
description = 'RLDP library'
edition = '2018'
name = 'rldp'
resolver = '2'
version = '0.7.68'

[workspace]

[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
log = '0.4'
rand = '0.7'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl.git', tag = '0.7.74' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto.git', tag = '0.1.25' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
raptorq = { path = 'raptorq', version = '1.2.1' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl.git', package = 'ton_api', tag = '0.2.128' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.2' }

[features]
telemetry = [ 'adnl/telemetry' ]
